# Generated by Django 4.1.6 on 2023-03-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=100000)),
                ("quantity", models.DecimalField(decimal_places=0, max_digits=10000)),
            ],
        ),
    ]
