# Generated by Django 4.1.6 on 2023-03-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="quantity", field=models.IntegerField(),
        ),
    ]
